### ISSUE TITLE
Does not work for go-1.8, "unrecognized profile format"

### ISSUE THREAD

**Issue by zoobenthos** [wirelessregistry/goprofui#3] opened 2017-03-06 12:31 UTC

**Comment by a-little-srdjan** [comment] 2017-03-06 16:01
Thanks for letting me know. I will look into the new data structure layout.

**Comment by damienstanton** [comment] 2017-03-10 18:25
@zoobenthos I was not able to reproduce this using Go 1.8 on macOS 10.12. Do you have a stack trace? From what I have seen, unrecognized profile format errors usually means a broken or outdated version of `pprof` itself.

**Comment by zoobenthos** [comment] 2017-03-10 19:18
Please look at my example: https://github.com/zoobenthos/goprofui_test
make
./test
browse localhost:6060
Profiling does not work for me (macOS 10.12.3, go-1.8, standard golang.org distribition https://storage.googleapis.com/golang/go1.8.darwin-amd64.pkg)
How to detect broken pprof?

**Comment by damienstanton** [comment] 2017-03-10 19:37
Hm... your test binary worked just fine for me. To see if pprof is working you can import it [per the docs](https://golang.org/pkg/runtime/pprof/).

That said, since its a std lib package you may want to try a complete clean out of your $GOPATH and reinstall Go.

**Comment by zoobenthos** [comment] 2017-03-10 19:50
I have reinstalled go-1.8 from scratch, removed all $GOPATH and clone only my example to $GOPATH/src/.
No, this does not working. Mystic. I mean FlameGraph only, plots working nice, I'm interested in working FlameGraph profiling.

**Comment by damienstanton** [comment] 2017-03-10 20:06
Ah, okay thanks for clarifying. I didn't know flame graphs were your problem. I'll play with my local fork and let you know what I find.

**Comment by julia-allyce** [comment] 2017-03-10 20:27
Hey I was able to replicate the issue. We are going to need to update internal/profile/profile.go for 1.8

**Comment by damienstanton** [comment] 2017-03-11 15:58
@julia-allyce #4 works for web example and @zoobenthos test code.

**Comment by a-little-srdjan** [comment] 2017-03-12 00:40
Thanks @damienstanton! Just merged your pull request.

**Closed as completed** 2017-03-12 00:40 UTC
Labels: bug
